# Generated by Django 5.1.6 on 2026-02-21 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=64)),
                ('table_name', models.CharField(max_length=128)),
                ('object_pk', models.CharField(max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['created_at'], name='accounts_au_created_606b86_idx'), models.Index(fields=['app_label', 'created_at'], name='accounts_au_app_lab_0e8f25_idx'), models.Index(fields=['model_name', 'created_at'], name='accounts_au_model_n_51a8ba_idx'), models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx')],
            },
        ),
    ]
