# Generated by Django 5.1.6 on 2026-02-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_purchaseorder_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_terms',
            field=models.CharField(default='As per Schedule', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='freight_terms',
            field=models.CharField(choices=[('extra_as_applicable', 'Extra as applicable'), ('included', 'Included')], default='extra_as_applicable', max_length=32),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='inspection_report_terms',
            field=models.CharField(default='Along with Material', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='packaging_ident_terms',
            field=models.CharField(default='Included', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='packing_terms',
            field=models.CharField(default='Standard Packing', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_pdc_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
