# Generated by Django 5.1.6 on 2026-02-28 08:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def populate_existing_po_item_rates(apps, schema_editor):
    PurchaseOrderItem = apps.get_model('purchasing', 'PurchaseOrderItem')
    for item in PurchaseOrderItem.objects.select_related('material').all():
        rate = item.material.cost_per_unit or Decimal('0')
        item.unit_rate = rate
        item.line_amount = (item.quantity or Decimal('0')) * rate
        item.save(update_fields=['unit_rate', 'line_amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaseorder_delivery_terms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='inventory_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='inventory_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_approved_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='line_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.RunPython(populate_existing_po_item_rates, migrations.RunPython.noop),
    ]
