# Generated by Django 5.1.6 on 2026-02-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_purchaseorder_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_pdc_days',
            field=models.PositiveIntegerField(default=45),
        ),
    ]
