# Generated by Django 5.1.6 on 2026-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_mroitem_current_stock_and_more"),
        ("purchasing", "0006_alter_purchaseorder_payment_pdc_days"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="purchaseorderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("received_quantity__lte", models.F("quantity"))),
                name="po_item_received_lte_quantity",
            ),
        ),
    ]
