# Generated by Django 5.1.6 on 2026-02-20 09:03

import django.db.models.deletion
from django.db import migrations, models


def seed_existing_vendor_links(apps, schema_editor):
    RawMaterial = apps.get_model("inventory", "RawMaterial")
    RawMaterialVendor = apps.get_model("inventory", "RawMaterialVendor")

    links = [
        RawMaterialVendor(material_id=material.id, vendor_id=material.vendor_id)
        for material in RawMaterial.objects.all()
    ]
    RawMaterialVendor.objects.bulk_create(links, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_links', to='inventory.rawmaterial')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_links', to='partners.partner')),
            ],
            options={
                'ordering': ['material__name', 'vendor__name'],
                'unique_together': {('material', 'vendor')},
            },
        ),
        migrations.RunPython(seed_existing_vendor_links, migrations.RunPython.noop),
    ]
