# Generated by Django 5.1.6 on 2026-02-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rawmaterialvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='material_type',
            field=models.CharField(choices=[('fabric', 'Fabric'), ('mesh', 'Mesh'), ('thread', 'Thread'), ('hardware', 'Hardware'), ('accessory', 'Accessory'), ('packaging', 'Packaging'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
