# Generated by Django 5.1.6 on 2026-02-21 07:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rawmaterial_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
    ]
