# Generated by Django 5.1.6 on 2026-02-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rawmaterial_cost_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='colour',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
