# Generated by Django 5.1.6 on 2026-02-22 09:01

from django.db import migrations, models


def backfill_material_ids_and_colour_codes(apps, schema_editor):
    RawMaterial = apps.get_model("inventory", "RawMaterial")
    for material in RawMaterial.objects.all().only("id", "colour", "rm_id", "colour_code"):
        updates = {}
        if not material.rm_id:
            updates["rm_id"] = f"RM-{material.id:04d}"
        if not material.colour_code:
            colour = (material.colour or "").strip()
            updates["colour_code"] = (colour[:12].upper() if colour else "NA")
        if updates:
            RawMaterial.objects.filter(pk=material.pk).update(**updates)


def reverse_backfill_material_ids_and_colour_codes(apps, schema_editor):
    # Keep user data unchanged on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rawmaterial_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='colour_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='rm_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(
            backfill_material_ids_and_colour_codes,
            reverse_backfill_material_ids_and_colour_codes,
        ),
    ]
