# Generated by Django 5.1.6 on 2026-02-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rawmaterial_variant_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
