# Generated by Django 5.1.6 on 2026-02-22 10:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_rawmaterial_code'),
        ('partners', '0002_partner_vendor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MROItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mro_id', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('tool', 'Tool'), ('factory_part', 'Factory Part'), ('machine_spare', 'Machine Spare Part'), ('other', 'Other')], default='other', max_length=32)),
                ('unit', models.CharField(choices=[('pieces', 'pieces'), ('set', 'set'), ('kg', 'kg'), ('m', 'm'), ('litre', 'litre')], default='pieces', max_length=16)),
                ('cost_per_unit', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mro_items', to='partners.partner')),
            ],
            options={
                'ordering': ['name', 'mro_id'],
            },
        ),
        migrations.CreateModel(
            name='MROInventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('ADJUST', 'ADJUST')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(max_length=16)),
                ('reason', models.CharField(max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='inventory.mroitem')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
