# Generated by Django 5.1.6 on 2026-03-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_mroitem_mroinventoryledger'),
        ('partners', '0002_partner_vendor_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rawmaterial',
            name='uniq_raw_material_rm_id_colour_code',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='pantone_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='colour_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('colour_code', ''), _negated=True), models.Q(('pantone_number', ''), _negated=True), _connector='OR'), name='raw_material_vendor_or_pantone_required'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.UniqueConstraint(condition=models.Q(('colour_code', ''), _negated=True), fields=('rm_id', 'colour_code'), name='uniq_raw_material_rm_id_vendor_colour_code'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterial',
            constraint=models.UniqueConstraint(condition=models.Q(('pantone_number', ''), _negated=True), fields=('rm_id', 'pantone_number'), name='uniq_raw_material_rm_id_pantone_number'),
        ),
    ]
