# Generated by Django 5.1.6 on 2026-04-14 08:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_inventoryledger_invoice_number"),
        ("partners", "0003_alter_partner_vendor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mroitem",
            name="current_stock",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="current_stock",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="mroitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_stock__gte", Decimal("0"))),
                name="mro_item_non_negative_stock",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawmaterial",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_stock__gte", Decimal("0"))),
                name="raw_material_non_negative_stock",
            ),
        ),
    ]
