# Generated by Django 5.1.6 on 2026-02-22 09:01

from django.db import migrations, models


def backfill_vendor_ids(apps, schema_editor):
    Partner = apps.get_model("partners", "Partner")
    for partner in Partner.objects.filter(vendor_id__isnull=True).only("id"):
        Partner.objects.filter(pk=partner.pk).update(vendor_id=f"VEND-{partner.id:04d}")


def reverse_backfill_vendor_ids(apps, schema_editor):
    # Keep user data unchanged on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='vendor_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(backfill_vendor_ids, reverse_backfill_vendor_ids),
    ]
