# Generated by Django 5.1.6 on 2026-02-22 08:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_planned_qty(apps, schema_editor):
    ProductionOrder = apps.get_model('production', 'ProductionOrder')
    for order in ProductionOrder.objects.all().only('id', 'quantity', 'planned_qty'):
        planned_qty = Decimal(order.quantity).quantize(Decimal('0.001'))
        ProductionOrder.objects.filter(pk=order.pk).update(planned_qty=planned_qty)


def reverse_backfill_planned_qty(apps, schema_editor):
    # Keep migrated values as-is on reverse for safety.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_production_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='planned_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='produced_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='scrap_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.RunPython(backfill_planned_qty, reverse_backfill_planned_qty),
        migrations.CreateModel(
            name='FinishedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_record', to='production.finishedproduct')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='FinishedStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('ADJUST', 'ADJUST')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('reason', models.CharField(max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='production.finishedproduct')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
