# Generated by Django 5.1.6 on 2026-02-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionorder_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='raw_material_released',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('awaiting_rm_release', 'Awaiting RM Release'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
