# Generated by Django 5.1.6 on 2026-02-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_mroitem_mroinventoryledger'),
        ('production', '0004_productionorder_raw_material_released_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bomitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bom_items', to='production.finishedproduct'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='item_type',
            field=models.CharField(choices=[('finished', 'Finished Product'), ('part', 'Part')], default='finished', max_length=16),
        ),
        migrations.AddField(
            model_name='productionconsumption',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.finishedproduct'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_usage', to='inventory.rawmaterial'),
        ),
        migrations.AlterField(
            model_name='productionconsumption',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial'),
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('part__isnull', True)), models.Q(('material__isnull', True), ('part__isnull', False)), _connector='OR'), name='production_bomitem_exactly_one_component'),
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.UniqueConstraint(condition=models.Q(('material__isnull', False)), fields=('product', 'material'), name='production_bomitem_product_material_unique'),
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.UniqueConstraint(condition=models.Q(('part__isnull', False)), fields=('product', 'part'), name='production_bomitem_product_part_unique'),
        ),
        migrations.AddConstraint(
            model_name='productionconsumption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('part__isnull', True)), models.Q(('material__isnull', True), ('part__isnull', False)), _connector='OR'), name='production_consumption_exactly_one_component'),
        ),
    ]
