# Generated by Django 5.1.6 on 2026-02-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_bomitem_unique_together_bomitem_part_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomitem',
            options={'ordering': ['product__name', 'id']},
        ),
    ]
