# Generated by Django 5.1.6 on 2026-03-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_bomitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='colour',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
