# Generated by Django 5.1.6 on 2026-04-14 06:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventoryledger_invoice_number'),
        ('production', '0008_finishedproduct_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_set', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
            ],
            options={
                'ordering': ['marker__marker_id', 'part__name'],
            },
        ),
        migrations.CreateModel(
            name='PartProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_length', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('actual_layers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('actual_sets_per_layer', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('total_sets', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('actual_fabric_issued', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('good_sets', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rejected_sets', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='target_type',
            field=models.CharField(choices=[('finished_product', 'Finished Product'), ('marker', 'Marker')], default='finished_product', max_length=24),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.finishedproduct'),
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_id', models.CharField(max_length=50, unique=True)),
                ('colour', models.CharField(blank=True, max_length=80)),
                ('sku_id', models.CharField(blank=True, max_length=50)),
                ('length_per_layer', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('sets_per_layer', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markers', to='inventory.rawmaterial')),
            ],
            options={
                'ordering': ['marker_id'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.marker'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('marker__isnull', True), ('target_type', 'finished_product')), models.Q(('product__isnull', True), ('marker__isnull', False), ('target_type', 'marker')), _connector='OR'), name='production_order_exactly_one_target'),
        ),
        migrations.AddField(
            model_name='markeroutput',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.marker'),
        ),
        migrations.AddField(
            model_name='markeroutput',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marker_outputs', to='production.finishedproduct'),
        ),
        migrations.AddField(
            model_name='partproduction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partproduction',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_productions', to='production.marker'),
        ),
        migrations.AddField(
            model_name='partproduction',
            name='production_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_production', to='production.productionorder'),
        ),
        migrations.AddConstraint(
            model_name='markeroutput',
            constraint=models.UniqueConstraint(fields=('marker', 'part'), name='production_markeroutput_marker_part_unique'),
        ),
    ]
