# Generated by Django 5.1.6 on 2026-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_markeroutput_partproduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='finishedproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'finished')), fields=('sku',), name='production_finishedproduct_finished_sku_unique'),
        ),
    ]
