# Generated by Django 5.1.6 on 2026-04-14 08:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0010_alter_finishedproduct_sku_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finishedstock",
            name="current_stock",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="finishedstock",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_stock__gte", Decimal("0"))),
                name="finished_stock_non_negative",
            ),
        ),
    ]
